apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vm55ap3oc-python 
  janus-idp.io/tekton: vm55ap3oc-python
  backstage.io/kubernetes-id: vm55ap3oc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vm55ap3oc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  