apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vm55ap3oc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vm55ap3oc-python 
  name: vm55ap3oc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vm55ap3oc-python 
